import "./components/MostrarImagen.jsx";
import "./components/Header.jsx";
import "./components/Carrito.jsx";
import "./components/Footer.jsx";
import "./components/BuscadorProductos.jsx";
import "./components/MiniCarrito.jsx";
import "./bootstrap";
import "./components/MostrarImagen.jsx";
import "./components/Register.jsx";
import "./components/Login.jsx";
import "./components/SearchInput.jsx";
import "./components/BreadCrumbs.jsx";
import "./components/Filtre.jsx";
import "./components/Profile.jsx";
import "./components/ShoppingOrder.jsx"
import "./components/shopProcess/shipping.jsx"
import "./components/BotonRedireccion.jsx"
import "./components/GuidedGeneration.jsx"
import "./components/ColorWheel.jsx"
import "./components/myImages.jsx"
import "./components/MyOrders.jsx"
import "./components/ViewDetails.jsx"
